"use strict";
let car = "Supra";
console.log("I can predict true");
console.log(car === "Supra");
console.log("I can predict false");
console.log(car !== "Supra");
console.log("I can predict true");
console.log(car == "Supra" && car.length < 6);
console.log("I can predict false");
console.log(car == "Supra" && car.length > 6);
console.log("I can predict true");
console.log(car == "Supra" || car.length > 6);
console.log("I can predict false");
console.log(car == "supra" || car.length > 6);
console.log("I can predict true");
console.log(car == "Supra" || car.length > 2);
console.log("I can predict false");
console.log(car != "Supra");
console.log("I can predict true");
console.log(car != "civic");
console.log("I can predict false");
console.log(car == "Supra" && 5 != 5);
