let places: string[] = ["Burj khalifa","Times square","Switzerland","South korea","Japan"]
console.log('Original ',places)
console.log('Copy+Sort ',[...places].sort())
console.log("Original ",places)
console.log("Copy+Sort+Reverse ",[...places].sort().reverse())
console.log("Original ",places)
console.log("Reverse " ,places.reverse())
console.log("Reverse " ,places.reverse())
console.log("Sort ",places.sort())
console.log("Sort+Reverse ",places.sort().reverse())